baseURL = "https://inge.4pr.es/"
# [en, zh-cn, fr, pl, ...] determines default content language
# [en, zh-cn, fr, pl, ...] è®¾ç½®é»˜è®¤çš„è¯­è¨€
defaultContentLanguage = "en"
# theme
# ä¸»é¢˜
theme = "uBlogger"
# themes directory
themesDir = "themes"

# website title
title = "INGE4PRES RATIONAL THOUGHTS"

# whether to use robots.txt
enableRobotsTXT = true
# whether to use git commit log
enableGitInfo = false
# whether to use emoji code
enableEmoji = true

[languages]
  [languages.en]
    weight = 1
    # language code
    languageCode = "en"
    # language name
    languageName = "English"
    # whether to include Chinese/Japanese/Korean
    hasCJKLanguage = false
    # default amount of posts in each pages
    paginate = 12
    # copyright description used only for seo schema
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
    # Menu config
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        pre = ""
        post = ""
        name = "About"
        url = "/about/"
        title = ""
        weight = 20
      [[languages.en.menu.main]]
        identifier = "resume"
        # you can add extra information before the name (HTML format is supported), such as icons
        pre = ""
        # you can add extra information after the name (HTML format is supported), such as icons
        post = ""
        name = "Resume"
        url = "/resume/"
        # title will be shown when you hover on this menu link.
        title = ""
        weight = 30
      [[languages.en.menu.main]]
        identifier = "tags"
        pre = ""
        post = ""
        name = "Tags"
        url = "/tags/"
        title = ""
        weight = 40
    [languages.en.params]
      # site description
      description = "Francesco Gualazzi: infrastructure-aware software engineer"
      # site keywords
      keywords = ["francesco gualazzi", "inge4pres", "blog", "devops", "software", "engineering", "SRE"]
      # App icon config
      [languages.en.params.app]
        # optional site title override for the app when added to an iOS home screen or Android launcher
        title = "INGE4PRES RATIONAL THOUGHTS"
        # whether to omit favicon resource links
        noFavicon = false
        # modern SVG favicon to use in place of older style .png and .ico files
        svgFavicon = ""
        # Android browser theme color
        themeColor = "#ffffff"
        # Safari mask icon color
        iconColor = "#5bbad5"
        # Windows v8-10 tile color
        tileColor = "#da532c"
      # Search config
      [languages.en.params.search]
        enable = true
        # type of search engine ("lunr", "algolia")
        type = "lunr"
        # max index length of the chunked content
        contentLength = 4000
        # placeholder of the search bar
        placeholder = "Find"
        # max number of results length
        maxResultLength = 20
        # snippet length of the result
        snippetLength = 30
        # HTML tag name of the highlight part in results
        highlightTag = "em"
        # whether to use the absolute URL based on the baseURL in search index
        absoluteURL = false
      # Home page config
      [languages.en.params.home]
        # amount of RSS pages
        rss = 16
        # Home page profile
        [languages.en.params.home.profile]
          enable = true
          # URL of avatar shown in home page
          avatarURL = "/images/avatar.png"
          # title shown in home page (HTML format is supported)
          title = "Francesco Gualazzi"
          # subtitle shown in home page (HTML format is supported)
          subtitle = "infrastructure-aware software engineer"
          # whether to show social links
          social = true
          # disclaimer (HTML format is supported)
          disclaimer = ""
        # Home page posts
        [languages.en.params.home.posts]
          enable = true
          # special amount of posts in each home posts page
          paginate = 16
      # Social config in home page
      [languages.en.params.social]
        Twitter = "inge4pres"
        GitHub = "inge4pres"
        Gitlab = "inge4pres"
        DockerHub = "inge4pres"
        Linkedin = "francescogualazzi"
        Instagram = "inge4pres"
        Facebook = "inge4pres"
        Keybase = "inge4pres"
        Stackoverflow = "4628081/francesco-gualazzi"
        Soundcloud = "Fringe"
        Spotify = "inge4pres"
        Email = "fgualazzi@gmail.com"
        RSS = true

[params]
  # uBlogger theme version
  version = "2.0.X"
  # site default theme ("light", "dark", "auto")
  defaultTheme = "auto"
  # public git repo url only then enableGitInfo is true
  # å…¬å…± git ä»“åº“è·¯å¾„ï¼Œä»…åœ¨ enableGitInfo è®¾ä¸º true æ—¶æœ‰æ•ˆ
  # gitRepo = "https://github.com/upagge/dolboblog-theme"
  # which hash function used for SRI, when empty, no SRI is used ("sha256", "sha384", "sha512", "md5")
  # å“ªç§å“ˆå¸Œå‡½æ•°ç”¨æ¥ SRI, ä¸ºç©ºæ—¶è¡¨ç¤ºä¸ä½¿ç”¨ SRI ("sha256", "sha384", "sha512", "md5")
  fingerprint = "sha256"
  # date format
  # æ—¥æœŸæ ¼å¼
  dateFormat = "2006-01-02"
  # website images for Open Graph and Twitter Cards
  # ç½‘ç«™å›¾ç‰‡, ç”¨äº Open Graph å’Œ Twitter Cards
  images = ["/images/avatar.png"]

  # Header config
  # é¡µé¢å¤´éƒ¨å¯¼èˆªæ é…ç½®
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    # æ¡Œé¢ç«¯å¯¼èˆªæ æ¨¡å¼ ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    # ç§»åŠ¨ç«¯å¯¼èˆªæ æ¨¡å¼ ("fixed", "normal", "auto")
    mobileMode = "auto"
    # Header title config
    # é¡µé¢å¤´éƒ¨å¯¼èˆªæ æ ‡é¢˜é…ç½®
    [params.header.title]
      # URL of the LOGO
      # LOGO çš„ URL
      logo = "/images/gopher.png"
      # title name
      # æ ‡é¢˜åç§°
      name = "INGE4PRES RATIONAL THOUGHTS"
      # you can add extra information before the name (HTML format is supported), such as icons
      # ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹å‰æ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
      pre = "<i class='fas fa-pencil-alt fa-fw'></i>"
      # you can add extra information after the name (HTML format is supported), such as icons
      # ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹åæ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
      post = "ğŸ¤“ <i class='fas fa-pencil-alt fa-fw'>Growing knowledge one post at a time</i>"

  # Footer config
  # é¡µé¢åº•éƒ¨ä¿¡æ¯é…ç½®
  [params.footer]
    enable = true
    # Custom content (HTML format is supported)
    # è‡ªå®šä¹‰å†…å®¹ (æ”¯æŒ HTML æ ¼å¼)
    custom = ''
    # whether to show Hugo and theme info
    # æ˜¯å¦æ˜¾ç¤º Hugo å’Œä¸»é¢˜ä¿¡æ¯
    hugo = true
    # whether to show copyright info
    # æ˜¯å¦æ˜¾ç¤ºç‰ˆæƒä¿¡æ¯
    copyright = true
    # whether to show the author
    # æ˜¯å¦æ˜¾ç¤ºä½œè€…
    author = true
    # site creation time
    # ç½‘ç«™åˆ›ç«‹å¹´ä»½
    since = 2012
    # ICP info only in China (HTML format is supported)
    # ICP å¤‡æ¡ˆä¿¡æ¯ï¼Œä»…åœ¨ä¸­å›½ä½¿ç”¨ (æ”¯æŒ HTML æ ¼å¼)
    #icp = ""
    # license info (HTML format is supported)
    # è®¸å¯åè®®ä¿¡æ¯ (æ”¯æŒ HTML æ ¼å¼)
    license= ''

  # Section (all posts) page config
  # Section (æ‰€æœ‰æ–‡ç« ) é¡µé¢é…ç½®
  [params.section]
    # special amount of posts in each section page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  # List (category or tag) page config
  # List (ç›®å½•æˆ–æ ‡ç­¾) é¡µé¢é…ç½®
  [params.list]
    # special amount of posts in each list page
    # list é¡µé¢æ¯é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡
    paginate = 20
    # date format (month and day)
    # æ—¥æœŸæ ¼å¼ (æœˆå’Œæ—¥)
    dateFormat = "01-02"
    # amount of RSS pages
    # RSS æ–‡ç« æ•°ç›®
    rss = 10

  # Comment config
  [params.comment]
    enable = true
    [params.comment.remark42]
      enable = false
      host = "https://comments.upagge.ru"
      site = "documentation"
      locale = "en"
    # Disqus comment config (https://disqus.com/)
    [params.comment.disqus]
      enable = true
      # Disqus shortname to use Disqus in posts
      shortname = "inge4pres"

  # Page config
  [params.page]
    # whether to hide a page from home page
    hiddenFromHomePage = false
    # whether to hide a page from search results
    hiddenFromSearch = false
    # whether to enable twemoji
    twemoji = false
    # whether to enable the ruby extended syntax
    ruby = true
    # whether to enable the fraction extended syntax
    fraction = true
    # whether to enable the fontawesome extended syntax
    fontawesome = true
    # whether to show link to Raw Markdown content of the content
    linkToMarkdown = true
    # whether to show the full text content in RSS
    rssFullText = false
    # Table of the contents config
    [params.page.toc]
      # whether to enable the table of the contents
      enable = true
      # whether to keep the static table of the contents in front of the post
      keepStatic = false
      # whether to make the table of the contents in the sidebar automatically collapsed
      auto = true
    # Code config
    # ä»£ç é…ç½®
    [params.page.code]
      # whether to show the copy button of the code block
      copy = true
      # the maximum number of lines of displayed code by default
      maxShownLines = 10
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = true
      Reddit = true
      Whatsapp = false
      Pinterest = false
      Tumblr = false
      HackerNews = false

    # Third-party library config
    # ç¬¬ä¸‰æ–¹åº“é…ç½®
    [params.page.library]
      [params.page.library.css]
        # someCSS = "some.css"
        # located in "assets/" ä½äº "assets/"
        # Or æˆ–è€…
        # someCSS = "https://cdn.example.com/some.css"
      [params.page.library.js]
        # someJavascript = "some.js"
        # located in "assets/" ä½äº "assets/"
        # Or æˆ–è€…
        # someJavascript = "https://cdn.example.com/some.js"
    # Page SEO config
    [params.page.seo]
      # image URL
      # å›¾ç‰‡ URL
      images = ["/images/avatar.png"]
      # Publisher info
      # å‡ºç‰ˆè€…ä¿¡æ¯
      [params.page.seo.publisher]
        name = "inge4pres"
        logoUrl = "/images/avatar.png"

  # Site verification code for Google/Bing/Yandex/Pinterest/Baidu
  # ç½‘ç«™éªŒè¯ä»£ç ï¼Œç”¨äº Google/Bing/Yandex/Pinterest/Baidu
  [params.verification]
    google = "TOk-oj9FYpVoRqq2BjvXT_OWQZZ6poZhp1WZXPhfMvE"

  # Site SEO config
  # ç½‘ç«™ SEO é…ç½®
  [params.seo]
    # image URL
    # å›¾ç‰‡ URL
    image = "/images/avatar.png"
    # thumbnail URL
    # ç¼©ç•¥å›¾ URL
    thumbnailUrl = "/images/gohper.png"

  # Analytics config
  # ç½‘ç«™åˆ†æé…ç½®
  [params.analytics]
    enable = true
    # Google Analytics
    [params.analytics.google]
      id = "UA-55252403-1"
      # whether to use gtag linked
      gtag = false
      # whether to anonymize IP
      # æ˜¯å¦åŒ¿ååŒ–ç”¨æˆ· IP
      anonymizeIP = true

  # Cookie consent config
  [params.cookieconsent]
    enable = true
    # text strings used for Cookie consent banner
    [params.cookieconsent.content]
      message = "Do you like cookies?"
      dismiss = "LGTM"
      link = "Learn more"

  # CDN config for third-party library files
  # ç¬¬ä¸‰æ–¹åº“æ–‡ä»¶çš„ CDN è®¾ç½®
  [params.cdn]
    # CDN data file name, disabled by default
    # ("jsdelivr.yml")
    # located in "themes/uBlogger/assets/data/cdn/" directory
    # you can store your own data files in the same path under your project:
    # "assets/data/cdn/"
    # CDN æ•°æ®æ–‡ä»¶åç§°, é»˜è®¤ä¸å¯ç”¨
    # ("jsdelivr.yml")
    # ä½äº "themes/uBlogger/assets/data/cdn/" ç›®å½•
    # å¯ä»¥åœ¨ä½ çš„é¡¹ç›®ä¸‹ç›¸åŒè·¯å¾„å­˜æ”¾ä½ è‡ªå·±çš„æ•°æ®æ–‡ä»¶:
    # "assets/data/cdn/"
    data = "jsdelivr.yml"

  # Compatibility config
  # å…¼å®¹æ€§è®¾ç½®
  [params.compatibility]
    # whether to use Polyfill.io to be compatible with older browsers
    # æ˜¯å¦ä½¿ç”¨ Polyfill.io æ¥å…¼å®¹æ—§å¼æµè§ˆå™¨
    polyfill = false
    # whether to use object-fit-images to be compatible with older browsers
    # æ˜¯å¦ä½¿ç”¨ object-fit-images æ¥å…¼å®¹æ—§å¼æµè§ˆå™¨
    objectFit = false

# Markup related configuration in Hugo
# Hugo è§£ææ–‡æ¡£çš„é…ç½®
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  # è¯­æ³•é«˜äº®è®¾ç½® (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  # Goldmark æ˜¯ Hugo 0.60 ä»¥æ¥çš„é»˜è®¤ Markdown è§£æåº“
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      # æ˜¯å¦åœ¨æ–‡æ¡£ä¸­ç›´æ¥ä½¿ç”¨ HTML æ ‡ç­¾
      unsafe = true
  # Table Of Contents settings
  # ç›®å½•è®¾ç½®
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Author config
# ä½œè€…é…ç½®
[author]
  name = "inge4pres"

# Sitemap config
# ç½‘ç«™åœ°å›¾é…ç½®
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks config (https://gohugo.io/content-management/urls/#permalinks)
# Permalinks é…ç½® (https://gohugo.io/content-management/urls/#permalinks)
[permalinks]
  posts = "/:year/:month/:day/:filename/"

# Privacy config (https://gohugo.io/about/hugo-and-gdpr/)
# éšç§ä¿¡æ¯é…ç½® (https://gohugo.io/about/hugo-and-gdpr/)
[privacy]
  # privacy of the Google Analytics (replaced by params.analytics.google)
  # Google Analytics ç›¸å…³éšç§ (è¢« params.analytics.google æ›¿ä»£)
  [privacy.googleAnalytics]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

# Options to make output .md files
# ç”¨äºè¾“å‡º Markdown æ ¼å¼æ–‡æ¡£çš„è®¾ç½®
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
# ç”¨äºè¾“å‡º Markdown æ ¼å¼æ–‡æ¡£çš„è®¾ç½®
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
# ç”¨äº Hugo è¾“å‡ºæ–‡æ¡£çš„è®¾ç½®
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
